sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: qJLQwjl8tApTvGxdkwtQXo1ML6NwO8RENyCbwkv5V4o55yWGzNnjIBB8aPZMVxVvbJCqBtsWSNrBrF0ZFMnc3f/Imbag836cXAdO259jWxti94ssLiHibqJ4xkwjdss5olBSfQEovq3TKTH2PY5hDtyQKo5qOFnVXkuA7EWmUN4T3zy1DwZdmlXsfyqNEhGWhL2NXB7xb5HnBu7bJGoChE85CWwu1ta5x+dIHV8CCWORQ/ZjtgREGSuJK3qrmpctIquSg0RumZDTZVqqXAm8rfi7A5Y6i26O9UPCGjfMboa62ibtyBD42OBvo7GKMtXvYPjSyF4g3uJN//R5VmmmHoMfxygMiPe6K+nxiNEf6z7Hjv/FC8MP+Sh8B+2iT9iJNZzIdSTUDICAazttbhJkTCH1K8qYHSjdZ36e3df0ff3GAi4McLBKaf3IzozgP27v/rZZqdLHa2Rz5T2L6VHmI6cCTAw3Z9sjDT5ti43TZ1KMtjCS7ifgZEYis3KOpMcadrEGtNHgggqPuh7LXm+TyicAo0Nf5vv21hcB4wM/kjkIBnfrmLltZ4+c1rySKvvAKxYUuB1jVM31m3FrGZv1QdjGliglKJUUkL3HYU1l04shwZdcj60cyNLyPetbVaMdtiuB6LkvK7pWyQxX/C5HwA83ToNIz2r0dPhWvZTw0UE=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Voyage-of-Verrazzano-A-Chapter-in-the-Early-History-of-Maritime-Discovery-in-America_5252
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy